### PR TITLE
Linux compatibility

### LINKED ISSUE #5: Add compatibility for Linux OS
The current implementation can be run only on Windows.
The problem arises when the optionicon.ico file has to be read by Tkinter.
Linux, however can not use .ico , instead it would require .xbm or .xmp.

Add conditional statements to determine if the OS is windows or Linux and add appropriate statements under each.
You are welcome to add the same functionality for Mac OS as well.

You can find the picture to be used, named as : **optionicon.png**

**To reproduce the issue**:
Run the .py file on a Linux OS.

**Expected output**:
Code should run without error

**Current output**:
tkinter.TclError...

### PR DESCRIPTION
**Pull request by RakshithRAcharya**
**Added Linux Comapatibility**

**I have created a gif of the icon and used that as the icon for the tkinter app**

**Linked Issue**  
Closes #5

### CODE REVIEW

**Review by srujandeshpande — APPROVED** [review]
Looks good!

**Comment by srujandeshpande** [comment]
!bounty 100

**Comment by srujandeshpande** [comment]
!bounty 0 pending approval

**Comment by sakshi2912** [comment]
hey @RakshithRAcharya , have you tried running this on a Linux OS? Cause in mine it still throws an exception
image

If it works in yours , can you show a Screenshot?
There is another instance where .ico is being referred to. You'll have to take care of that as well

**Comment by RakshithRAcharya** [comment]
Take a look at this

**Comment by srujandeshpande** [comment]
Looks good. @sakshi2912, works for me on Ubuntu 20.04

**Comment by sakshi2912** [comment]
> 
> Take a look at this

But when you click on create strategy, you get this error:
image

**Comment by RakshithRAcharya** [comment]
Got it Got it....will make changes and submit PR again

**Pull request closed without merging**
