### PR TITLE
Linux2

### PR DESCRIPTION
**Pull request by RakshithRAcharya**
**Fixed Issue #12 **

**Corrected the issue with linux comptibility**

**Linked Issue**  
Closes #12

### CODE REVIEW

**Comment by sakshi2912** [comment]
Perfect! I'll merge this.

**Comment by sakshi2912** [comment]
!bounty 110

**Comment by sakshi2912** [comment]
!bounty 50

**Comment by RakshithRAcharya** [comment]
@sakshi2912 Why was bounty points reduced

**Pull request merged**
